#!/bin/bash

# Automated Railway Variable Sync Script
# This script runs during deployment to sync environment variables

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Railway Variable Auto-Sync ===${NC}\n"

# Check if railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo -e "${RED}Error: Railway CLI not installed${NC}"
    echo "Install it with: npm install -g @railway/cli"
    exit 1
fi

# Railway environment check (optional - works locally too)
if [ -n "$RAILWAY_ENVIRONMENT" ]; then
    echo "Running in Railway environment: $RAILWAY_ENVIRONMENT"
fi

# Check for .env.local first, then .env
if [ -f .env.local ]; then
    ENV_FILE=.env.local
    echo "Using .env.local file..."
elif [ -f .env ]; then
    ENV_FILE=.env
    echo "Using .env file..."
else
    echo -e "${YELLOW}Warning: No .env or .env.local file found, skipping sync${NC}"
    exit 0
fi

echo "Syncing variables to Railway..."
echo ""

# Get Railway public domain for URL conversion
RAILWAY_DOMAIN=$(railway variables --kv 2>/dev/null | grep "^RAILWAY_PUBLIC_DOMAIN=" | cut -d'=' -f2)
if [ -z "$RAILWAY_DOMAIN" ]; then
    # Fallback to static URL
    RAILWAY_DOMAIN=$(railway variables --kv 2>/dev/null | grep "^RAILWAY_STATIC_URL=" | cut -d'=' -f2)
fi

if [ -n "$RAILWAY_DOMAIN" ]; then
    echo "Detected Railway domain: $RAILWAY_DOMAIN"
    echo "Will auto-convert localhost URLs to production URLs"
    echo ""
fi

# Collect all variables to set in a single command
VARS_TO_SET=()

# Parse .env file and collect variables
while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines and comments
    if [[ -z "$line" ]] || [[ "$line" =~ ^#.*$ ]]; then
        continue
    fi

    # Extract key=value
    if [[ "$line" =~ ^([^=]+)=(.*)$ ]]; then
        key="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]}"

        # Remove inline comments from value
        value=$(echo "$value" | sed 's/#.*//' | sed 's/[[:space:]]*$//')

        # Remove quotes if present
        value=$(echo "$value" | sed 's/^"//' | sed 's/"$//')

        # Skip if value is empty or a placeholder
        if [[ -z "$value" ]] || [[ "$value" == *"your_"* ]] || [[ "$value" == *"_here"* ]]; then
            echo -e "${YELLOW}Skipping $key (empty or placeholder)${NC}"
            continue
        fi

        # Skip Railway auto-generated and localhost-specific variables
        if [[ "$key" == "DATABASE_URL" ]] || [[ "$key" == "REDIS_URL" ]] || \
           [[ "$key" == "REDIS_HOST" ]] || [[ "$key" == "REDIS_PORT" ]] || \
           [[ "$key" == "REDIS_PASSWORD" ]]; then
            echo -e "${YELLOW}Skipping $key (auto-generated by Railway)${NC}"
            continue
        fi

        # Auto-convert localhost URLs to production URLs
        if [[ -n "$RAILWAY_DOMAIN" ]] && [[ "$value" == *"localhost:3000"* ]]; then
            original_value="$value"
            value="${value//http:\/\/localhost:3000/https://$RAILWAY_DOMAIN}"
            echo -e "${YELLOW}Converting $key: localhost → $RAILWAY_DOMAIN${NC}"
        fi

        # Auto-convert NODE_ENV to production
        if [[ "$key" == "NODE_ENV" ]] && [[ "$value" == "development" ]]; then
            value="production"
            echo -e "${YELLOW}Converting NODE_ENV to production${NC}"
        fi

        # Add to variables array
        VARS_TO_SET+=("--set" "$key=$value")
        echo "✓ Will set $key"
    fi
done < "$ENV_FILE"

# Execute all variables in a single command if we have any
if [ ${#VARS_TO_SET[@]} -gt 0 ]; then
    echo ""
    echo -e "${GREEN}Setting ${#VARS_TO_SET[@]} variables...${NC}"
    railway variables "${VARS_TO_SET[@]}" --skip-deploys
    echo -e "${GREEN}✓ Variables synced successfully!${NC}"
else
    echo -e "${YELLOW}No variables to sync${NC}"
fi

echo ""
echo -e "${GREEN}=== Sync Complete ===${NC}"
